### ISSUE TITLE
Low timeout causes false positives

### ISSUE THREAD

**Issue by atmadja40** [freearhey/iptv-checker#1]
When i specify low timeout eg:10ms or even 1ms, all the links are marked as "online" even if they are not.

**Comment by freearhey** [comment]
This is the expected behavior. The script marks the link as broken only if it receives an error in response. And `timeout` parameter controls only the time to wait for a response from the server.

**Comment by atmadja40** [comment]
Ok thank you, I understand.
Is it possible to plan an option to get the opposite behavior : Class the link as offline when no response was get from the server before the timeout ?

**Comment by freearhey** [comment]
I will think about it.

**Comment by freearhey** [comment]
@atmadja40 I decided to eventually change the default behavior. Now as soon as the request time comes out the link will be marked as offline.
