### ISSUE TITLE
Missing Test Script

### ISSUE THREAD

**Issue by detroitenglish** [freearhey/iptv-checker#11]
Running `npm run test` should execute `test/index.js`; however, this file doesn't seem to exist 🤷‍♂️

If you already have this script for testing, then it just needs to be added to the repo. 

Otherwise, again I'd be happy implement this myself (using something like `ava`?). Just let me know what you think!

**Comment by freearhey** [comment]
No, there are no more tests. So it'd be great if you could write a few.
