### ISSUE TITLE
multiple user agents in a single playlist

### ISSUE THREAD

**Issue by Mattheo1985** [freearhey/iptv-checker#18]
Hi there,

the streams in my example will only work with a specific user-agent. iptv-checker allows me to define a global user-agent. Is there a way to define the user-agents individually?

Would it be possible to respect the user agent defined in the #EXTVLCOPT attribute? 

```
#EXTM3U

#EXTINF:-1,Stream 1
#EXTVLCOPT:http-user-agent=VLC/3.0.9.2
http://sample.net/stream1.m3u8

#EXTINF:-1,Stream 2
#EXTVLCOPT:http-user-agent=FooBar/1.2.3
http://sample.net/stream2.m3u8
```

`iptv-checker -a 'VLC/3.0.9.2' -k sample.m3u`

- Stream 1 = Online
- Stream 2 = Offline

`iptv-checker -a 'FooBar/1.2.3' -k sample.m3u`

- Stream 1 = Offline
- Stream 2 = Online

**Comment by freearhey** [comment]
Yes, I am familiar with this case and I have already asked the owner of `iptv-checker-module` on the basis of which this package now works to add this feature: https://github.com/detroitenglish/iptv-checker-module/issues/5

**Comment by Mattheo1985** [comment]
Sorry, I didn't dig that deep.  I'll watch the referenced issue. Thanks!

**Comment by freearhey** [comment]
I'll be fine with any option.
