### ISSUE TITLE
mark as duplicate because same tv-logo cover

### ISSUE THREAD

**Issue by Manssizz** [freearhey/iptv-checker#21]
hi.. i have issue when check tv serial with same cover image source but different movie file source
iptv-checker mark as duplicate. so... iptv-checker only check one file with same image cover source. are this tool can't check playlist with same image cover source? this my playlist sample mark as duplicate. i have 60 eps with same cover
 ```
#EXTINF:-1 tvg-logo="" group-title="VOD MOVIES",Insya Allah Sah 2 (2018)
http://srv24.nf21.net:80/files/10-2018-11-04-dcbe1927ad12c18b3d39efe1e310b3b5.mp4
#EXTINF:-1 tvg-logo="" group-title="VOD MOVIES",Arini (2018)
http://srv19.nf21.net:80/files/15-2018-08-19-4e022676b9971cfac33a65d84288c01d.mp4
#EXTINF:-1 tvg-logo="" group-title="VOD MOVIES",Benyamin Biang Kerok (2018)
http://srv19.nf21.net:80/files/15-2018-08-14-2a88269fa86b8dab2575101a66eb0732.mp4
#EXTINF:-1 tvg-logo="" group-title="VOD MOVIES",Bodyguard Ugal-Ugalan (2018)
http://srv24.nf21.net:80/files/11-2018-11-09-4d0f5e263c6bc227c1b23c5145c32713.mp4
#EXTINF:-1 tvg-logo="" group-title="VOD MOVIES",Flight 555 (2018)
http://srv19.nf21.net:80/files/15-2018-08-14-f0ddc7cdffd608547912ad3a1b33056f.mp4
 ```

**Comment by freearhey** [comment]
I'm sorry, but I have not been able to reproduce your issue. This utility basically only compares broadcast links when searching for duplicates, so channel logo should not affect the result.
