### ISSUE TITLE
Is testing RTP streams possible?

### ISSUE THREAD

**Issue by sbeu** [freearhey/iptv-checker#22]
Hello,
I have an m3u file with RTP streams links. When I execute, the output is:

```
iptv-checker testliste.m3u

Total: 0
Online: 0
Offline: 0
Duplicates: 0
```

Here is my m3u file:

```
#EXTM3U
#EXTINF:0,rtp://239.193.132.161:1234
rtp://@239.193.132.161:1234
#EXTINF:0,rtp://239.193.128.33:1234
rtp://@239.193.128.33:1234
```

Note that the streams are on a private network. 

My questions: 
1) Is the list badly formatted? I created it from VLC
2) Are RTP streams supported?

Thank you

**Comment by freearhey** [comment]
Thank you for pointing that out. Indeed earlier all links that had a protocol other than `http` and `https` were filtered out. 

I have already changed this and in `v0.19.0` other protocols should also pass all tests including `rtp`.
