### ISSUE TITLE
Time Out

### ISSUE THREAD

**Issue by AgSapri** [freearhey/iptv-checker#23]
Microsoft Windows [Version 10.0.19042.1110]
(c) Microsoft Corporation. All rights reserved.

C:\Users\acer>iptv-checker C:\Users\acer\Desktop\test.m3u
[===] 3/3 (100%)

Total: 3
Online: 0
Offline: 3
Duplicates: 0

#EXTM3U
#EXTINF:-1, TV1 (Timed out)
https://rtmklik.rtm.gov.my/tv/1
#EXTINF:-1 ,TV2 (Timed out)
https://rtm1.secureswiftcontent.com/Origin01/ngrp:RTM1/playlist.m3u8
#EXTINF:-1 ,TV3 (Timed out)
https://stream-03.sg1.dailymotion.com/sec(_9ERdFwnAbs1GZsc1AwhHY634iz1M9H7ztC85bpw0JE)/dm/3/x6qp375/d/live-3.m3u8

**Comment by freearhey** [comment]
I got the following results:

iptv-checker test.m3u -o output
[===] 3/3 (100%) 

Total: 3
Online: 1
Offline: 2
Duplicates: 0

output/offline.m3u

```
#EXTM3U
#EXTINF:-1, TV1 (Invalid data found when processing input)
https://rtmklik.rtm.gov.my/tv/1
#EXTINF:-1 ,TV2 (Server returned 403 Forbidden (access denied))
https://rtm1.secureswiftcontent.com/Origin01/ngrp:RTM1/playlist.m3u8
```

output/online.m3u

```
#EXTM3U
#EXTINF:-1 ,TV3
https://stream-03.sg1.dailymotion.com/sec(_9ERdFwnAbs1GZsc1AwhHY634iz1M9H7ztC85bpw0JE)/dm/3/x6qp375/d/live-3.m3u8
```

Do the links work well in the player?

**Comment by AgSapri** [comment]
yes.. it shud like that., 
huhu

**Comment by AgSapri** [comment]
ill try everythng reinstall npm and package nothing wrong but result still same i got offlin times out

**Comment by freearhey** [comment]
Have you tried any other links besides these three?

**Comment by AgSapri** [comment]
i did.. all offline

C:\Users\acer>iptv-checker C:\Users\acer\iptv-checker\test\input\example.m3u
[==] 2/2 (100%)

Total: 2
Online: 0
Offline: 2
Duplicates: 0

C:\Users\acer>iptv-checker C:\Users\acer\iptv-checker\test2.m3u
[====] 4/4 (100%)

Total: 4
Online: 0
Offline: 4
Duplicates: 0

#EXTM3U
#EXTINF:-1 ,BBC News (Timed out)
http://1111296894.rsc.cdn77.org/LS-ATL-54548-6/index.m3u8
#EXTINF:-1 ,Edge Sport (Timed out)
https://imgedge.akamaized.net/amagi_hls_data_imgAAA2AA-edgesports/CDN/playlist.m3u8
#EXTINF:-1 ,Free Sport (Timed out)
https://csm-e-stv.tls1.yospace.com/csm/live/203444271.m3u8
#EXTINF:-1 ,Reuters Now (Timed out)
https://reuters-reutersnow-1.plex.wurl.com/manifest/playlist.m3u8

**Comment by freearhey** [comment]
I don't know what the problem could be, but maybe someone else has encountered this problem and can help.

**Comment by freearhey** [comment]
As of `v0.22.0` the default timeout has been increased and now the check should give the correct result. Let me know if this is not the case and the problem is still relevant.
