### ISSUE TITLE
[enhancement] add limit bandwidth usage

### ISSUE THREAD

**Issue by Manssizz** [freearhey/iptv-checker#25]
hi.. can you add bw usage for checking?
ie, i want check some playlist with limit 2Mb connection i have
and proxy for checking playlist. because some host blocked ip outside their country 
thank you

**Comment by freearhey** [comment]
I don't plan to add such a feature, but you can implement it yourself using iptv-checker as a node.js module 
in the repo description you can find an [example](https://github.com/freearhey/iptv-checker#nodejs) how to get all the data you need for this
