### ISSUE TITLE
different resaults from same Commands

### ISSUE THREAD

**Issue by KomuSei** [freearhey/iptv-checker#3]
[root@xzyjs ~]# iptv-checker /sample/* -o /sample/iptv_check -t 60000
============================================================================================================================================================
Total: 156. Online: 83. Offline: 67. Duplicates: 6.
[root@xzyjs ~]# iptv-checker /sample/* -o /sample/iptv_check -t 60000
============================================================================================================================================================
Total: 156. Online: 84. Offline: 66. Duplicates: 6.

**Comment by freearhey** [comment]
Could you provide an example of a playlist?

**Comment by KomuSei** [comment]
> Could you provide an example of a playlist?

http://iptv.xzyjs.xyz/iptv_Homenet_%E7%94%B5%E6%8A%A5%E7%BE%A4%E5%8F%8B%E7%BB%B4%E6%8A%A4/Homenet.m3u
this link is exactly what i used

**Comment by freearhey** [comment]
The fact is that not all servers from which broadcasts are running stable. Even with a small load they start to produce errors. You can see the same result if you use this playlist in VLC player. And unfortunately, it is impossible to calculate in advance when the error is temporary and when it is not.
