### ISSUE TITLE
Server returned 4XX Client Error, but not one of 40(0,1,3,4)

### ISSUE THREAD

**Issue by Owyn** [freearhey/iptv-checker#31]
Can we have an explicit error returned for 451 (same meaning as 403) error reported?

cuz now we get `Server returned 4XX Client Error, but not one of 40(0,1,3,4)` instead for it

![image](https://user-images.githubusercontent.com/1309656/160118786-a472fa84-f377-41c1-817a-5f5949d89069.png)

451 is returned for geo-blocked content by some providers instead of 403 forbidden

**Comment by freearhey** [comment]
I will definitely update the package as soon as [this](https://trac.ffmpeg.org/ticket/9700) request is approved and a new version of ffprobe will appear.

**Comment by freearhey** [comment]
Implemented in `v0.24.0`
