### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Manssizz** [freearhey/iptv-checker#5]
i have few playlist iptv, only one succes checking. other playlist have same eror like this
![image](https://user-images.githubusercontent.com/23637327/75337166-0db22d00-58bf-11ea-8d91-17238790a014.png)
whats wrong?

**Comment by freearhey** [comment]
Most likely a problem with the playlist syntax. For example, there is a lack of closing quotes.
