### ISSUE TITLE
Timeout Validation

### ISSUE THREAD

**Issue by freearhey** [freearhey/iptv-checker#8]
In the last release, the timeout check was disabled to prevent duplication on the output. 

The problem is that the built-in timer in `ffprobe` does not work in most cases and can delay the check of one broadcast to infinity. 

But what makes the situation even more complicated is that `ffprobe` also lacks a built-in process stop mechanism. That is, even if you run a regular timer parallel to the main check and it finishes the countdown earlier, you have no way to stop the check in `ffprobe` and prevent duplicates in the output.

If there is any good solution, I will definitely turn on the timeout check back, but at this point I decided to just turn it off completely.

**Comment by detroitenglish** [comment]
You can, however, [kill the parent `ffmpeg` process](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#controlling-the-ffmpeg-process). So I disabled native `ffprobe` timeout errors in #9 , and our timeout function now kills the parent `ffmpeg` on resolve.

Tests are passing so I think it should work! 👍

**Comment by freearhey** [comment]
Unfortunately, stopping the `ffmpeg` process has no effect on `ffprobe`. 

I wrote about it last year: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/959 And somebody's already done a proper PR: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/pull/976 But nothing has changed since then 😕

**Comment by detroitenglish** [comment]
OK, thanks for validating this for me. I've never worked with `ffmpeg` before. 

Out of curiosity, is `ffprobe` built into `ffmpeg`, or is it a standalone binary? For example, if `ffmpeg` were compiled as a WebAssembly module, would it be possible to call `ffprobe` from the browser? Or would `ffprobe` need to be compiled separately?

**Comment by freearhey** [comment]
I'm not very familiar with `ffmpeg` to answer your questions either, but in the case of [fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg) `ffprobe` definitely depends on it: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/12667091eeea09b0d6a55b87eb886aa131178608/lib/ffprobe.js#L96

**Comment by freearhey** [comment]
Fixed in [v0.15.0](https://github.com/freearhey/iptv-checker/releases/tag/v0.15.0)
